version: "3.1"
services:
  database:
    image: mysql:5.7
    volumes:
      - ./mysql/db/entrypoint:/docker-entrypoint-initdb.d/
    ports:
      - "3301:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=zikade3301"
      - "MYSQL_DATABASE=Modulhandbuch"